### ISSUE TITLE
How to switch ''vim-mode-plus:move-[up/down]" to "vim-mode-plus:move-[up/down]-wrap"

### ISSUE THREAD

**Issue by abers** [t9md/atom-vim-mode-plus#1023]
I am trying to find a way to enable j/k to move up/down when using soft-wrap in [zen mode](https://atom.io/packages/zen). I noticed in the vim-mode-plus.cson file that vim-mod-plus:move-[up/down]-wrap were commented out. Uncommented them and commented the 'vim-mode-plus:move-[up/down]' instead but it seems to have no effect.

**Comment by t9md** [comment]
- `vim-mode-plus:move-up-wrap` and `vim-mode-plus:move-down-wrap` is NOT what you are finding.
- It's up/down command to wrap from first last-row to first-row, first-row to last-row.
- What you are finding is `g k` and `g k`, it move up/down in screen row instead of buffer row.
- If you want to replace default `j` and `k`, set following keymap in your `keymap.cson`

```coffeescript
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'k': 'vim-mode-plus:move-up-screen'
  'j': 'vim-mode-plus:move-down-screen'
```
