### ISSUE TITLE
Vertical block selection skips lines with whitespace

### ISSUE THREAD

**Issue by bendavis78** [t9md/atom-vim-mode-plus#107]
When pressing <kbd>ctrl + v</kbd> and doing a vertical block selection, the selection seems to skip lines if there's whitespace. It doesn't seem to behave this way in vim.

![screencast](https://cloud.githubusercontent.com/assets/324392/12061349/1dd56838-af49-11e5-9ef3-46142a2f28f5.gif)

**Comment by t9md** [comment]
OK, I know, but I'm OK, I won't aiming to complete mimic of Vim's behavior.
Its trade off of implementation simplicity vs introducing code complexity trying to being perfect compatibility to pure Vim.

By the way, you reported a lots of issue.
It's OK, but I expect you to respond each of issue you reported after I responded something.

Especially I want to solve error, stability issue rather than these compatibility matter-of-taste issue.
