### ISSUE TITLE
Feature Request: Transform object literal from single to multi line

### ISSUE THREAD

**Issue by bennypowers** [t9md/atom-vim-mode-plus#1119]
Hello! I ❤️ vmp. thank you so much for publishing it.

I often find myself transforming snippets like this:

```js
const {
  hasTooltipContent,
  icon,
  originalFill,
  position,
  size,
  tooltip,
} = this;
```
to this:
```js
const { hasTooltipContent, icon, originalFill, position, size, tooltip } = this;
```
and vice-versa. 

I'd like it if there was a general operation to toggle this sort of thing.

Contrast current work flow:
to collapse object: <kbd>shift-J</kbd> as many times as needed
to expand object: <kbd>f space l s return</kbd> as many times as needed, then manually adjusting indentation.

with a potential workflow:

<kbd>g z i {</kbd>

for "toggle collapse inner object".

Thank you for considering this feature.

# Checklist

- [x] Pick a descriptive and non-ambiguous subject
- [x] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [x] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [x] Include real use case so that maintainer can understand "why" you need help.

**Comment by t9md** [comment]
I understand your background.
However, vmp currently does not provide the exact feature you what.

Here is how we can do in your scenario with the current vmp feature..

## For multi-line to a single line

Select area, then remove "\n" by `J`, then let `prettier` format to remove extra `,` or manually remove it.

## For single-line to multi-line

Use `split-arguments` operator.
Keystrokes should be `g , i {`.(mine is `g , ;` since I use shorthand keymap which allow me to use a semicolon as `inner-any-pair` text-object).


You can find some info for `arguments` tex-object and related operator in this old release notes.
https://github.com/t9md/atom-vim-mode-plus/blob/master/CHANGELOG.old.md#0890


![Untitled](https://user-images.githubusercontent.com/155205/55558723-a5e37880-5727-11e9-9d40-ef8debeb9257.gif)

**Comment by bennypowers** [comment]
![mind blown](https://media.giphy.com/media/l0HlJvfTsnXJ7l2LK/giphy.gif) Amazing. Thanks!
