### ISSUE TITLE
Question: visual mode's compatibility with atom's editor movements

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#112]
To what extent will visual mode's selection be compatible with atom's editor commands? For example, I'd like to be able to use `editor:move-to-previous-subword-boundary` in conjunction with the visual mode. It might require lots of changes to the code logic though so I'm fine with the current state of things I think.

(Thanks again for your work all this time btw)

**Comment by t9md** [comment]
From normal mode, if you create some selection via non-vim-mode-plus's commands, it automatically change mode to 'visual-characterwise' mode.

From visual mode, if you use `editor:move-to-` kinds commands it clear selection, so mode changed to normal. Because move-to kinds command use `cursor.setBufferPosition()` internally it clear selection.

From visual mode, if you use `editor:select-to-` kinds commands it extend selection, mode remains visual-mode since selection is not empty.

So for your question, as long as you use `editor:select-to` kinds commands its somewhat compatible with visual-characterwise mode.
Where incompatible is

- When selection is reversed via outer-vim-mode-plus's commands, tail range(where you start visual-mode) is not included. 
 e.g. text: 'abc',  `v` at 'b' char select 'b', then `h` or ,`l` always keep 'b' selected, but not for outer-vim-mode-plus's command.

- Cursor visibility is not updated.

If you want to make it completely compatible, need to define motion as vim-mode-plus's command?

What you want is adding subword motion as vim-mode-plus's commands?

**Comment by chenglou** [comment]
I was seeing what I could do for #44 when I stumbled upon this behaviour. If that's how things are then I'm fine with it. If you don't think you'll make `move-to-*` more compatible with visual mode, then feel free to close this issue!

**Comment by t9md** [comment]
I re-opened #44.
So close this issue.
I'll try to evaluate how it is by implementing feature.

**Comment by chenglou** [comment]
Btw, as it is I've set up keybindings such as `'cmd-L': 'editor:select-to-next-subword-boundary'`. This works really fine since I'm dropped into visual mode after selection anyway. For deletion and others I'd just select first, no biggie.

So for me at least, vim-mode-plus specific subword features is low-priority. I was just curious =).

**Comment by t9md** [comment]
Thanks for noting that.
I just want to how much it is useful by implementing , evaluating it.
I used to thought subword is to small portion to move around but not sure.
What kind of situation, identifier you think its useful I'm curious it.

**Comment by t9md** [comment]
@chenglou 
Btw, I wrote HOW-TO extend vmp in [this page](https://github.com/t9md/atom-vim-mode-plus/wiki/Extend-vmp-by-adding-your-own-Motion-TextObject-Operator).

You can add your own motion in your `init.coffee` until I implement it.  
The main advantage of implementing as vmp command is it's became available as operator's target.
So you can `d`, `c` then your own motion command, off-course repeatable by `.`.

**Comment by crshd** [comment]
That's great. I didn't really think of subwords until i saw this, but I implemented it right away. Now all I need is `a subword` and `inner subword`, for all the times I have to change `thisMethod` to `thatMethod`...

I'm not too sure about the binding, though. Right now I'm using `ctrl-b` and `ctrl-e` for previous and next subwords, but I believe motion commands shouldn't use a modifier. But then again, the keyboard is already packed with bindings, it's basically impossible to add something else.

**Comment by t9md** [comment]
@crshd Yeah, choosing appropriate default keybinding is very difficult and impossible.
That's why I disabled most of vim-mode-plus's specific original motion/text-object/operator keybinding by default.

I also tried subword motion by implementing very draft version.
Then, many opinion poped up in my mind so, I want to think further for a while.
 - I want skip `.`, `@` for CoffeeScript  when moved by its depending of language.
 - I want subword text object to change or expand selection by subword like
    e.g. when you map `.` to `inner-subword` text-object
       `c.` to change subword, `v..` to expand selection to next, next subword.

**Comment by crshd** [comment]
- `inner-subword` can be achieved by extending `TextObject` with Atom's `Cursor.subwordRegExp()`, which will select based on the `editor.nonWordCharacters`, which can be configured based on language.

- That would be a great to have, as well, but not completely necessary.
I've changed some bindings, now `q` does `next-subword`, while `i q` is `inner-subword`. So I can select concurrent subwords with `v i q q`.

**Comment by t9md** [comment]
Could you share your code via Gist?
I just want to see other people extend vmp.

**Comment by crshd** [comment]
As usual, I forgot to push my changes before leaving work today. But I will put it up on Monday.

**Comment by crshd** [comment]
There we go: https://gist.github.com/crshd/794ecd79f6afefeaae80

It's very simple, but it does the job.

**Comment by t9md** [comment]
@crshd Wow! you also created text-object for that.
Thanks for sharing.
I think you don't need to call `@extend()` for `TextObject.Subword`.
Currently its used internally and calling it register your operation as vmp registries so that can be used by other operation.
Unless you expecting your operation is used by other operation(defined in different place). You don't have to call `@extend()` and shouldn't.
But I'm writing  from my memory maybe I missed something :smile: ...

**Comment by crshd** [comment]
Thanks for the input. I oriented myself on `WholeWord`. Originally I added this directly in `text-object.coffee`, but then decided to keep it in my init, so it won't get overwritten by updates :D 

I was going to test and maybe refine it for a while before submitting a pull request.

**Comment by chenglou** [comment]
> What kind of situation, identifier you think its useful?

Super useful for multi cursor selection, e.g. selecting the occurrences of a same prefix/suffix.

Or batch subword moficaitions:

```
sayHelloToYou
sayHelloWithMe
sayHelloFromPeople
```
Subword navigation allows me to batch change from e.g. `sayHelloToYou` to `youSayHello` (same pattern for the other two). Place one cursor per line, at the beginning. Jump to end, subword select You/Me/People, delete, subword delete To/With/From, jump to beginning, paste, lower case. Will probably work with macros too.

Also, when I miswrite `helloWorld` into `helloWodld` I typically just remove the `Wodld` part using subword deletion and rewrite.

**Comment by t9md** [comment]
Thanks for explaining practical use case I'll evaluate and try to tune my daily editing operation by @crshd 's [plugin](https://atom.io/packages/vim-mode-plus-subword-movement) and your example.

After that, I will decide to include(or not) submode operation as default.
