### ISSUE TITLE
`cib` on multiline parens deletes one line too many

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#141]
Repro:

```
(
  a
  b // cursor here
  c
)
```

Do `cib`

Expected:

```
(
// cursor here
)
```

Actual:

```
(
) // cursor on )
```

The above behaviour is correct for `dib`. `cib` leaves an empty line.

**Comment by t9md** [comment]
OK, this is the side effect of #135 to fix #131 you reported.
`c` change behavior if target is linewise or not, since I disabled auto submode shift for `iB`, current behavior you reported in this issue is `c`'s characterwise behavior.
Pure Vim is already inconsistent and I don't want to case-by-case behavior differentiation.
But I understand what you want, I agree to fix this issue.
Want some time to re-think better consistent way..

Thanks for reporting.

**Comment by chenglou** [comment]
I see. I file these issues by comparing against pure vim as reference. But if pure vim is inconsistent and we can do better, then I'm totally fine deviating from it.

**Comment by t9md** [comment]
Yes, agree, but as I spend time for vmp and check pure Vim behavior frequently than before, pure Vim well designed for UX perspective.
And find pure Vim giving up internal inconsistency for intuitiveness for developer(editing person).

For this particular issue my direction is to fix to conform with pure Vim's behavior.

**Comment by t9md** [comment]
Fixed.
Quick fix, but not bad.
