### ISSUE TITLE
Question: What does this TODO item mean?

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#15]
>>  Don't change cursor position after yank, indent, toggle(break compatibility to Vim, but I thinks this is bettter).

I checked, and it seems that this plugin matches Vim's behavior. I like the fact that it matches Vim's behavior.

**Comment by t9md** [comment]
I want to provide option to change current Vim's behavior.
When you hank in visual-line mode, cursor is put left-top position of original selection.
Also `yip`, `yiw` move cursor from original position.
One of this benefit is let user notice operation succeeded when text-object is used as operator's target.
But I don't want move cursor after operation finished.

Since I provided feature to flash range where operator operate on, I want to provide option to stay same cursor position after operation like (yank, indent, etc).

Partially implemented for  `gU`, `gu` like string transformation, you can check the behavior by enabling  `stayOnTransformString`. and `gUiw`. or `g/ip`(comment out paragraph) etc...
