### ISSUE TITLE
Cursor movement in visual mode is much slower than normal Atom.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#162]
When selecting a line with `v`, and moving down `j`, it is unbearably slow on a lower powered computer (Mac 12 inch). However, when selecting using insert mode (holding down shift and moving arrow keys), it is much faster (this is regular Atom selection IIRC).

I have a very fast key repeat rate. I tried to do some basic profiling to determine the cause, but could not find any bottleneck in the profiler.

**Comment by t9md** [comment]
I want to improve this.
Yes, theoretically It must be much slower than native Atom selection expansion thins it add lots of operations.
But I can't tell speed diff at least with my notebook blow.

 - MacBook Pro Retina 13-inch Mid 2014
 - CPU: 2.6GHz Intel Core i5
 - Memory: 16GB
 - OS X 10.9.5

To investigate
- You don't feel slowness when you switched to other computer? Is that main computer you use?
- Speed change if you disable softwrap(in case you enabled softwrap)?
- Recently I added `highlightSearch` feature, from then highlight refreshing happen on each scroll event, how about installing the version before `highlightSearch` was supported by `apm install vim-mode-plus@v0.20.0`
- How about using github's `vim-mode` to compare this issue is specially observed in vmp.
- How about commenting out [these lines](https://github.com/t9md/atom-vim-mode-plus/blob/master/lib/base.coffee#L51-L54).

There are a lot of thing I can do to improve.
Want to know where I have to tune.
But I don't want to do blindly as long as I'm not suffered from this slowness.

Btw, one of the big frustrating thing for atom or atom+vmp when compared to Vim is its **slowness**, **delay**, **responsiveness** against user keystroke.

**Comment by crshd** [comment]
Can confirm on my work computer. It's not so much _slow_, maybe just a bit. But I can see it kind of stutter - jump ~5 lines, short pause, jump another couple of lines, ...

- iMac 21.5-inch mid-2010
- 3,06GHz i3
- 4GB RAM
- OS X 10.10.5

> You don't feel slowness when you switched to other computer? Is that main computer you use?

IIRC the problem is not present on my slightly newer, more powerful MBP. I'll check it when I get home.

> Speed change if you disable softwrap(in case you enabled softwrap)?

No.

> Recently I added highlightSearch feature, from then highlight refreshing happen on each scroll event, how about installing the version before highlightSearch was supported by apm install vim-mode-plus@v0.20.0

I'm still on v0.19

> How about using github's vim-mode to compare this issue is specially observed in vmp.

vim-mode is fine, it's vmp.

> How about commenting out these lines.

From what I can tell it doesn't make a difference.

**Comment by t9md** [comment]
@crshd Thanks for checking for each!

> vim-mode is fine, it's vmp.
This info is very helpful to investigate further.

Can you see slowness only in visual mode or simple `j` stroke in normal mode also slow?

**Comment by jordwalke** [comment]
It is still very slow when `Show Cursor In Visual Mode` is disabled.

**Comment by jordwalke** [comment]
> Btw, one of the big frustrating thing for atom or atom+vmp when compared to Vim is its slowness, delay, responsiveness against user keystroke.

I totally agree. VMP is approaching very high quality compatibility with the "feel" of Vim, but the thing that appears to be getting in the way is Atom itself. (Maybe vmp has a very small portion of the fault, but I think in general, there is much low hanging fruit in Atom. If those issues in Atom are fixed, VPM gets better).

**Comment by t9md** [comment]
At least now my main use of Atom is developing vmp itself.
I'm now experimenting to understand how vim works and how I can improve or extend it to provide better editing experience.

My optimistic expectation is computer CPU get faster as long as Webkit's JavaScript engine get faster, and Atom itself tuned to be performant, this issue is gradually disappear.

Another good news neo-vim growing people who don't stand Atom's slowness can chose neo-vim.

I like atom and atom's vim-mode for its hack-ability. Touch core part via JavaScript and experiment it.
For example, vmp provides `stayOnOperate` feature but how it would be hard to support same feature in pure Vim.

**Comment by t9md** [comment]
I want to know if 
- Slowness is particularly in visual-mode(or also affects normal-mode).
- Slowness is specific for `j`, not `k`

One big difference of `j` from official vim-mode is `j` always have to check the row is vim's EOF.
Since native atom allows put cursor on last empty newline vmp specially disallow this by checking cursor is at last empty newline or not when moved down direction.

So if you don't see same issue with `k`, the cause should be this difference.

**Comment by fkjogu** [comment]
I also experience this lag when moving horizontally with `h` or `l` in visual mode.
My feeling is, that moving up with `k` is slightly more responsive than downwars.

**Comment by t9md** [comment]
What kind of machine are you using, spec please cpu memory and OS?

**Comment by fkjogu** [comment]
Intel i7 Haswell, 8 GB DDR-3 RAM, Debian 8, using current stable version of Atom. So reasonable hardware, I'd presume.

**Comment by t9md** [comment]
I can tune some of the part of vim-mode-plus so that skip duplicate EOL check like caching result.

But my priority for this topic is very low.
I know performance is very important but low priority for following reason.

Atom is not performant editor.
Tweaking vim-mode-plus' side is less contribution for whole performance.
When I need edit big file(like 15K lines of log file), I still use vim, Atom is useless for this use.
So my strategy is to postpone performance tuning of vim-mode-plus's  side to avoid introducing complexity by that tuning.

But if someone suggest architecture improvement for this area as long as code example or pull request.
I'll of course welcome and check it.

I'll keep this issue open since it's critical issue but not having solution right now.

**Comment by marcosfede** [comment]
Hi, Visual mode is quite laggy for me ( core i7 920, 10gb ram, ssd ) when "show cursor in visual mode" is enabled.
If I disable it, it is much better but it still lags a lot if I visually select lots of lines of code (like 20+)  in visual block mode.

**Comment by t9md** [comment]
This is old issue, both atom and vmp changed drastically from when this issue was reported.
Still performance is important for for Atom and vmp, but I have nothing to do particular for this issue.
Close because no TODO left for this issue.
