### ISSUE TITLE
String selection bugs when another double quote nearby

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#173]
Repro:

```
bla: '"'                       "hello world"
             ^ cursor here        ^ or here
```

Expected: `vi"` works at both locations
Actual: works on first location only.

**Comment by t9md** [comment]
understand your point.
As far as I checked behavior of pure Vim. It is simpler than current vmp implementation.
vmp count number of quote and check if its even or odd number to determine its open quote or close quote.
I'll check to implement more stupidly simple way to work as like pur Vim.
Thanks for rerpoting.

**Comment by t9md** [comment]
I noticed some trade-off to fix this.
Here is the diff of vmp vs pure Vim.

In following text
```
foo: '"'            "hello world"
              ^ cursor    ^ or here

bar: "hello"           "world"
              ^ cursor
```

To express behavior diff simply
 - vmp try to select only inner-quote area not area between quote-end and quote-start.
 - Vim select simply between two quote char.
 
In `foo:` line, `vi"`
 - vmp: select first location only, cannot select "hello world" since quote('"') number within same line is not even. YES this is BUG and want to FIX if I can!
 - Vim: can select both 1st and 2nd location

In `bar:` line, `vi"` from cursor position
 - vmp: select "world" by moving cursor. which is also useful when change `ci"`.
 - Vim: select area betweeen end of `hello` and start of `world`.

In later(`bar:`) case vmp is doing better(in my opinion of course).
This is because vmp(this behavior is exits from original vim-mode) check where is the `inner-quote` by counting `"` char.
So behavior you reported is trade-off of this behavior.
Trying to fix toward stupidly select area between left `"` and right `"` approach breaks behavior in bar line.

So in quick impression
I think situation like `foo:` line is not many and in that case want to workaround by tedious movement.
As conclusion, at least for me `ci"` in `bar:` line is more prioritized than foo lines compatibility to pure Vim.

To fix `foo:` case, approach should be when counting quote char, it should be counted per quoted-area based, not whole-line based.
But it seems a bit hard, I have no idea for now.

**Comment by bronson** [comment]
I just ran into this, on this very line: https://github.com/t9md/atom-vim-mode-plus/blob/a7b9eefe2f85241063c92b8512a9b66fad6c13e1/spec/motion-general-spec.coffee#L627

@t9md, I think that only works when the quoted strings are all on the same line.  Many languages allow multi-line quotes: bash, ruby, coffeescript, etc.  How would you handle those?  It seems like you'd always have to scan from the start of the document.

Personally, I prefer reliable stupid behavior over unreliable smart behavior.  :)

**Comment by t9md** [comment]
> Personally, I prefer reliable stupid behavior over unreliable smart behavior. :)

Me too, so I want fix this(just low-prioritized over other issue).

**Comment by t9md** [comment]
Done, will included in next release.
