### ISSUE TITLE
Ability to use `vmp` as state machine for other editor?

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#182]
Would it be possible to use `vmp` as a state machine for another editor? It seems like `vmp` is one of the most faithful `vim` recreations that I've seen. It would be a pretty big deal if it could be used in a variety of editors - it would be much easier for others to collaborate on than neovim. I understand one challenge is that it doesn't implement its own insert mode.

Please close as this is just a question.

**Comment by t9md** [comment]
Any practical example in your mind? I can't imagine how "state machine for another editor" like.

**Comment by t9md** [comment]
Anyway I don't think its possible.
Since currently vmp greatly depending on Atom's imprementation detail, and its underlying tex-buffer npm package.

If I could truly implement vim's behavior like I described [before](https://github.com/atom/vim-mode/issues/800), it will get more easier to use as vmp from other editor, but its too far from current dev state. 
And again my intention is not mimic pure Vim's feature completly, I want just borrow useful feature and concept from pure Vim in additon to introducing lots of original motion, text-obj and operator for to be able to edit in flashing speed.

**Comment by jordwalke** [comment]
I agree with everything you say. I like `vpm` *better* than vim. It's just that I want `vmp` on top of a blazing fast text buffer. So either the community should invest time/resources to make Atom's text buffer much more responsive, or make a completely new text buffer implementation (maybe not even compatible with Atom's) that uses `vpm` as a state machine. Either way, I am happy.

**Comment by t9md** [comment]
Btw, did you read above issue I opend on official vim-mode?
After I put that notes, I started refactoring experiment of vim-mode to make every motion, text-object, operation PURE. This experiment leads current vmp.
Still I can't achieve original intention and many motion depends Atom's imperative cursor movement commands. It have side effect, so I can't make motion only return final position.
So this would be my dream.
I want make each motion, text-obj only return position and let operator update some state and render final state as view like React or Elm embracing.
If I have time, then I want to try to recreate vim-mode with Elm on top of Atom's text-buffer.
That would be fun!

**Comment by jordwalke** [comment]
> So this would be my dream.

Me too!

**Comment by jordwalke** [comment]
Also, if it is mostly pure, you could render to a very lightweight GL representation.
