### ISSUE TITLE
Cannot move tab when it is in normal mode

### ISSUE THREAD

**Issue by hanwentao** [t9md/atom-vim-mode-plus#193]
A tab cannot be moved if it is in normal mode.

**Comment by t9md** [comment]
I cannot understand, whats the issue?

**Comment by hanwentao** [comment]
![image](https://cloud.githubusercontent.com/assets/225030/13730073/fc4fe5dc-e97f-11e5-9440-1799c3c53b7a.png)

Sorry for confusion.  I mean normally you can drag the tab title to rearrange its position in the bar.  However, when vmp is enabled, the tab title cannot be dragged when it's in normal mode.

**Comment by t9md** [comment]
Strange, I can move tab by dragging title even if vmp enabled and `normal-mode`.
Your issue is only happen in normal-mode? How about insert-mode, visual-mode..

**Comment by BinaryMuse** [comment]
I've been having the same issue since I last updated (I cannot recall which version I had installed previously). Clicking on a new tab to attempt to drag it causes the tab to gray out but does not allow it to be dragged:

![vmp-tabs-issue](https://cloud.githubusercontent.com/assets/189606/13732894/673cbcb8-e948-11e5-81e0-28bfe055efaa.gif)

The issue does not happen if the editor in a tab is in insert mode, and once a tab has been grayed out, putting the editor into insert mode makes it draggable again. Leaving insert mode and attempting to drag it again fails.

**Comment by t9md** [comment]
@BinaryMuse thanks.
I checked 1.5.4, and 1.6.0-beta6 on my MacOS X 10.9.5.
But I can drag and move.
I believe this is definitely BUG of vim-mode-plus..
But first I want to find way to reproduce.

**Comment by BinaryMuse** [comment]
@t9md Interesting, I can reproduce using vmp 0.24.0 on Atom 1.5.4.

![vmp-tabs-issue-2](https://cloud.githubusercontent.com/assets/189606/13734599/d803746e-e95c-11e5-8f42-0dc97b28a540.gif)

For what it's worth I dug through the code earlier today trying to track this down and didn't find anything. =\

**Comment by t9md** [comment]
@BinaryMuse 
Comment out these line solve problem?
These are only place where vmp handle mouse event.

https://github.com/t9md/atom-vim-mode-plus/blob/master/lib/vim-state.coffee#L187-L191

**Comment by BinaryMuse** [comment]
@t9md I'm suddenly having a tougher time reproducing the problem — I will continue to investigate and get you more info asap

**Comment by BinaryMuse** [comment]
I suddenly started seeing this again, so I commented out the indicated lines and the problem persisted. I'm still working on a minimum setup that reproduces the issue.

**Comment by BinaryMuse** [comment]
Gah, finally — I tracked this down to `disableInputMethodExceptInsertMode`; I can only repro when the option is enabled.

**Comment by hanwentao** [comment]
Make sense.  Confirmed.

**Comment by t9md** [comment]
Oh! Thanks @BinaryMuse I'll chek to fix that.
Thanks for nwrrowing down, this is great contribution.

**Comment by t9md** [comment]
Introduced in https://github.com/t9md/atom-vim-mode-plus/issues/148

**Comment by t9md** [comment]
Still investigating.
When I set `@hiddenInputElement.setAttribute('type', 'password')` in mode except insert-mode(e.g normal-mode), this make tab-bar undraggable.

Checked event triggerd, when issue is happening, `onDragOver` event in tab-var-view is not fired.

https://github.com/atom/tabs/blob/master/lib/tab-bar-view.coffee#L52

But when I split-pane like `cmd-k right`, then tab-bar become draggable again, it also breaks disableIME feature meaningless( still input type is password, but no longer disable IME when escaped from insert-mode).

I feel this `disableInputMethodExceptInsertMode` feature is already broken when it is introduced.
So I'm in mood to remove this immature confusing feature.

**Comment by t9md** [comment]
After I did investigation and found `disableInputMethodExceptInsertMode` is not always works even after paying cost of "give up drag&drop tab", I decided to remove `disableInputMethodExceptInsertMode` feature.
So as a result, this issue is solved.

This is not ideal fix.
But leaving semi-broken feature breaks another feature is worse.
So removed it.

Thanks for @BinaryMuse to clearing the root cause.
