### ISSUE TITLE
Change inner word eats extra character in some cases

### ISSUE THREAD

**Issue by shayne** [t9md/atom-vim-mode-plus#22]
Thanks for all of your work on this plugin! Happy to contribute if you point me in the right direction.

Here's my bug, `[ ]` denotes normal cursor position, `|` denotes insert cursor position:
`foo([b]ar)` then issue `ciw` for change-inner-word
Result:
`foo|)`

What's really annoying is inserting the eaten parentheses results in `foo())`

**Comment by t9md** [comment]
Yes its shoud be fixed I ll check day after tomorrow.
I dont hace access to PC now.
Anyway thank you for reporting.

**Comment by t9md** [comment]
Its already fixed in official vim-mode.
I also did fix in this issue but better in case cursor is left column of delimiter(its not taken care of in official vim-mode).

NOTE, Currently this kind of inconsistency between visual-mode and operator is exists in all over the place. Fixing this inconsistency resolve similar kind of problem in future, so this is quick and dirty fix.

I have idea and know what to do to fix this problem completely but need some time and should be treated in separate issue.

I'll close this issue after I release fixed version( I need to fix another issue before release).

**Comment by t9md** [comment]
Released v0.1.8.

**Comment by shayne** [comment]
Great, thanks! Tested and works. Did require an Atom restart, however.
