### ISSUE TITLE
Keybinding for french keyboard

### ISSUE THREAD

**Issue by metal3d** [t9md/atom-vim-mode-plus#28]
Hi, 
There is a problem with keybindings on AZERTY keyboard. For example to hit "/" we need the shift key. So it seems that the package doesn't resolve the shortcut (keybinding resolver tells I'm hitting shift+/)

That's probably why I cannot use the search, visual block and so on... 

Note: I installed and setup keyboard-localization package for french

**Comment by t9md** [comment]
So you can  invoke search(`/`) by mapping `shift-/` in your keymap.cson like this?

```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'shift-/': 'vim-mode-plus:search'
```

I don't want add keymap for special keyboard(I mean non-US keyboard).

**Comment by metal3d** [comment]
What I've done is to stop the keyboard-localization. And that works for now. What I mean is that pressing "shift+/" does the work when I stop the localization plugin. But now I've got to press "ctrl+ù" to toggle treeview; and so on. So it's not your plugin that have a problem :)

But, that doesn't fix the visual block... I cannot use it (and I really need it, without this, I will be back on Vim). Maybe I have to open another bug report because it seems that the "mode" is active, but selection is not ok. It's not the same problem.

AFAIK atom developpers don't want to change the keybinding system (I realize that the problem exists on my own nw.js softwares) and I can imagine that there will be a lot of bug report as mine in the futur. Because the keyboard-localization fixes some binding, but breaks others as yours.

Anyway, thanks a lot (and congrats for your nice plugin, I didn't passed to atom without a powerfull vim binding plugin, and yours is very complete, I just need the "normal" mode to be able to use ":"... ex-mode won't work with you plugin)

**Comment by t9md** [comment]
For visual block, what atom keybinding resolver says?
And please describe version(Atom, vim-mode-plus)

For ex-mode, you can make request to ex-mode's issue.
I don want implement ex-mode for now.

**Comment by metal3d** [comment]
Visual block says that it's ok, but moving cursor still use a caracter selection. See my screencast:

![anim](https://cloud.githubusercontent.com/assets/100080/11211286/a5897536-8d2e-11e5-922e-89f5c908534b.gif)

**Comment by t9md** [comment]
I can't understand whats the problem is from your screencast.

By activating keymap resolver with `cmd-.' then ensure
- `c-v` mapped to `vim-mode-plus:activate-blockwise-visual-mode` and ensure mode indicator on right bottom status bar become 'Visual Block'
- then `j` mapped to `vim-mode-plus:blockwise-move-down`.

How is your environment.
Please describe issue more specifically including version.
Currently I can't still figure out its issue of vim-mode-plus or other generic keymap issue.

**Comment by metal3d** [comment]
Ok, I didn't tried with "j" key... I used to hit "arrow down" (that is not a good habit ;) 

To clarify, you can see in my screencast that C-v activated "Visual Block" (bottom right information) and when I pressed arrow, the selection was not blockwise.

left and right arrows are ok, I can understand that you probably cannot set "down" and "up" arrow keys to blockwise selection. So I will now use "j" and "k".

Thanks a lot for your help and sorry for the bad issue.

**Comment by t9md** [comment]
Oh, I understand your problem, you use arrow key to move cursor up/down.
The reason I didn't map arrow key is just I didn't cared since I never use arrow key for movement.
There is no technical reason to prevent me arrow key map to blockwise-up/down.

I'll update vim-mode-plus's defaut keymap later and release in a few day.

Untill then, you can add mapping on your keymap.cson.
Just map `up` and `down` key by checking [Here](https://github.com/t9md/atom-vim-mode-plus/blob/master/keymaps/vim-mode-plus.cson#L303-L311).

**Comment by metal3d** [comment]
Thanks a lot. To be honest I'm a newbie on Atom (10 years of using Vim) - I will try to map them as you explained. 

PS: sorry to forget to give versions, I used to give them when I create reports, I don't know what happend in my head when I written this issue ;)

**Comment by Tuxie** [comment]
I have fought with similar problems using Swedish keymap for over 20 years. I have never been able to use many of the common shortcuts in a lot of applications, like ctrl-], ctrl-[ and ctrl-\ that so many apps use were just out of the question.

About two years ago I switched to US keyboard layout everywhere except in the web browser. The only place I need to write åäö is in the web browser anyway. It gets surprisingly easy to switch back and forth after a while. My life is so much easier now!

On the other hand, since the French layout is not QWERTY you should make a custom "US-AZERTY" keymap were you only switch around the A-Z letters to match AZERTY, but keep the rest like US layout.

**Comment by t9md** [comment]
I understand both of you.
I'm Japanese and Japanese have also Japanese-keyboard layout although its layout is variant of US keyboard(not as big difference form US layout as yours).

But I prefer to use US keyboard since most application shortcut is designed to easily accessible from US keyboard.
