### ISSUE TITLE
tree-view supports

### ISSUE THREAD

**Issue by jimzhan** [t9md/atom-vim-mode-plus#302]
it'd be more efficient for previous vi/vim users :-)

**Comment by t9md** [comment]
Not sure what feature do you want?

**Comment by jimzhan** [comment]
maybe like the NERDTree, you can efficiently move to basically anywhere like we normally do in VIM, plus copy the file/folder names etc.

**Comment by t9md** [comment]
Atom already have [tree-view](https://atom.io/packages/tree-view) package and some packages which essentially add keymap to walk through each node in tree like NERDTree.
check out [nerd-treeview](https://atom.io/packages/nerd-treeview) which I haven't tried yet.
At minimum you can add some keymap in your `keymap.cson` to get keyboard based navigation in tree-view, but I know it's not completely like NERDTree, but I don't want to re-implement by myself.
This is Atom not Vim, golden rule is to do your best to make you adapt to Atom's way.

**Comment by t9md** [comment]
> maybe like the NERDTree, you can efficiently move to basically anywhere like we normally do in VIM, plus copy the file/folder names etc.

The reason why this is difficult is, in Atom tree-view is not simple text-editor.
Its express tree-view using HTML and CSS instead of text and syntax highlight like NERDTree.

Theoretically someone can re-create NERDTree with text and syntax-highlight on top of Atom's text-editor. But I won't try that on this package(vim-mode-plus).
