### ISSUE TITLE
ex-mode

### ISSUE THREAD

**Issue by davibe** [t9md/atom-vim-mode-plus#32]
Hi,

i like your plugin. For me it works better than vim-mode. The only thing i miss is ex-mode because i am used to doing :linenumber or :50% to jump to move around. Is this planned ? is there something already available ?

**Comment by t9md** [comment]
No. And I have no plan to implement by myself(I dont't need ex-mode in Atom at least currently).
Its easy to implemtnt by modifying ex-mode package, ask ex-mode's author id you want.

For :linenber I map `:` to the go-to-line( originally mapped to c-g).
For N% I will make N% feature available from normal-mode as like in pure Vim.

**Comment by davibe** [comment]
Very clear, thank you

**Comment by t9md** [comment]
I added N% command, will release in a few days.

I think I can implement ex-mode(or command-mode), but I'm not in that mood since this is Atom, not Vim.
We can invoke command from command-palette.
I don't want two command palette in one editor.

(Of course the feature is very different but this is main reason which make me reluctant to implement ex-mode).
