### ISSUE TITLE
Repeat Command Ignores Insert-Mode Backspaces

### ISSUE THREAD

**Issue by diminutivesloop** [t9md/atom-vim-mode-plus#322]
When using the repeat command to repeat a sequence of insert mode edits, any instance of backspace is ignored. For example if I execute the `A` command followed by a backspace and escape, the repeat command does nothing. The expected behavior is to delete the last character of the current line whenever the repeat command is executed.

**Comment by t9md** [comment]
Sorry for slow response, I understand the issue, but very difficult to solve.
Technically it's not impossible I believe, but hard and not so motivated to fix this.
So current my judge is wont-fix or postpone for years.

Thak you for reporting.

**Comment by xh3b4sd** [comment]
I am having the same issue. Repeating insert mode backspace is one essential feature I am used to in vim. Having no support for this in Atom is really odd. What does it take to solve this issue?

**Comment by t9md** [comment]
@xh3b4sd  Before I really tackle to solve this issue, I want to understand practical situation.

- Sample text(before/after/after-repeat)
- Keystrokes in each step.

Since I cannot imagine situation where this backspace repeat is really useful.
So I'm not very motivated to supportinsert-mode-backspace-repeat.

**Comment by xh3b4sd** [comment]
I am hitting this issue on a daily basis. Imagine the following. I have a list of paths I want to modify.

```
/some/path/
/my/path/
/yet/another/path/
```

The result should look like this.

```
/some/path
/my/path
/yet/another/path
```

Or like this.

```
/some/path.ext
/my/path.ext
/yet/another/path.ext
```

What I do in VI is this. 

- go to the first line I want to change
- shift-A
- backspace to remove what I want to remove in each line
- insert what I want to insert in each line
- esc
- j
- repeat as often as I want to change lines using `.`

vim-mode-plus also does not support makros, at least not that I am aware of. Usual makro recording does not work using q at least. So because of the missing support for repeatable backspaces I am fooling around some times and get distracted by missing features my usual habits expect to exist. I need this for manipulation of several lists of text. For instance rewriting import paths of golang packages in my case or variable/constant definitions. Consider this.

```
var (
	MatchHead EventType = "match-head"
	MatchTail EventType = "match-tail"
	MatchBody EventType = "match-body"
	MatchPath EventType = "match-path"
	MatchGlob EventType = "match-glob"
)
```

Should become this. 

```
var (
	MatchHead EventType = "match-head-event"
	MatchTail EventType = "match-tail-event"
	MatchBody EventType = "match-body-event"
	MatchPath EventType = "match-path-event"
	MatchGlob EventType = "match-glob-event"
)
```

I can understand that my examples might seem to be arbitrary or only little comprehensible, but my experience in the last days is that I miss it somehow. Maybe it is because of some inefficient habits though. What do you think? Is there something I can do to work around these cases?

**Comment by t9md** [comment]
@xh3b4sd I like your style of issue report.

Thanks for practical example/usecase I always need this kind of practical situation to evaluate the importance of enhancement.

First, I understand use case, that motivate me to tackle this issue. Thanks.

Second, without supporting repeat-char-removing-operation-done-in-insert-mode, you can have other way to achieve this.
I'll explain how to do this.


## Remove trailing `/` from each line

```
/some/path/
/my/path/
/yet/another/path/
```

1. Place cusor to 1st line
2. `ctrl-v j j $ A`, you are now `inser-mode`, with three cursor is at end of line.
3. hit `backspace` then `ecape`, you are now `normal-mode`, trailing `/` was removed from each-line.

## Add `-event` suffix to end-of-each-string

```
var (
    MatchHead EventType = "match-head"
    MatchTail EventType = "match-tail"
    MatchBody EventType = "match-body"
    MatchPath EventType = "match-path"
    MatchGlob EventType = "match-glob"
)
```

1. Place cursor on 2nd line(`MachedHead` line).
2. `v i i` to select same indent-level
3. `ctrl-v I ctrl-e ctrl-b`, you are now `insert-mode` with each cursors at before last `"` char.
4. Type `-event`.

For step 3. there is several way(such as `ctrl-v $ A ctrl-b`).
The point is, in Atom using power of multiple-cursors is sometimes more efficient than `.` repeat on each-line one-by-one.
