### ISSUE TITLE
Better visual indication of active mode

### ISSUE THREAD

**Issue by Hibryda** [t9md/atom-vim-mode-plus#356]
It's a proposal to enhance vim-mode-plus. While it's not a big issue it could be convenient to have a large visual indication of an active mode. Something like this:

![screenshot from 2016-09-06 10 41 56](https://cloud.githubusercontent.com/assets/7373208/18267425/56e5e6d4-741f-11e6-9539-43993bb89365.jpg)

I know it's not very attractive in this form, I just sketched it fast and pinned to background. It's SVG, so it's very light. It's also fixed. If it would be considered I can make few versions of such backgrounds as a contribution.
It can be made better further by providing user with options to set custom opacity and color for each state.

**Comment by t9md** [comment]
At least for me, I don't need visual indication for mode, since I no longer confuse about state of mode, since I keystroke by understanding which is operator, which cause state change to operator-pending to wait target(=motion, text-object).

But for beginner vim user, this kind of visual indication would help.
I prefer changing cursor-line depending on mode approach.

https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#highlight-cursor-line-differently-depending-on-current-mode

You can create and release vim-mode-plus's helper package.
https://github.com/t9md/atom-vim-mode-plus/wiki/Create-vmp-plugin

Or might be modify your `init.coffee`
https://github.com/t9md/atom-vim-mode-plus/wiki/Extend-vmp-in-init-file

Or If you could put fragment code, I can conclude to to form to set user's `init.coffee`.

Thanks for suggestion by the way.

**Comment by Hibryda** [comment]
I'm hardly a beginner in vim, also have no special problems with discerning the mode, but I also smoke :) . This causes that after a while smoking outside I return and sometimes want to write and then I realize that I'm in normal or block V. Not a big issue actually, but I sometimes like to spice things visually.
Will see, in my free time I probably will write a plugin - just not to search, where VMP exposes mode? I saw that there is no event emitted on it (or maybe it is?)

**Comment by t9md** [comment]
https://github.com/t9md/atom-narrow/blob/master/lib/main.coffee#L81

This package use that hook to provide vmp integration here.

**Comment by Hibryda** [comment]
Perfect. So there is event :) If I made this plugin will let know. Thanks

**Comment by t9md** [comment]
Looking forward to that!
