### ISSUE TITLE
Feature Request: Animated scroll.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#382]
I enjoy `vim-mode-plus:scroll-half-screen-up`, but it would be great if there was an animated version which used some kind of easing function. Not a super important feature, but would be nice.

**Comment by t9md** [comment]
I like this idea and want to evaluate.
Don't know how to implement, (periodically set scrollTop by calculating from final scrollTop and duration?)

Want to know some sample code.

**Comment by jordwalke** [comment]
There's another plugin for animated scrollTo. It would even be kind of fun to have it be an option when searching with `n`/`N` because it gives you visual context about the direction in the file you are navigating (otherwise, you have to look at the scrollbars or line number).

**Comment by t9md** [comment]
I'll start experiment by implementing it for scroll motion.

**Comment by t9md** [comment]
Done quick and easy implementation using jQuery, vmp is already depending jquery indirectly since vmp using `space-pen-views` in several parts.

I can not release this as-is, current implementation don't care `c-f` repeated in very short time.
In this case, we should animate last `c-f` only.

I think I would implement `vimState.requestAnimate` to request jQuery's animation, if another request comes in, previous request is settled or `vimState.finishAnimation()` immediately finish animation by calling `done` callback which callback is finalResult of animation.

So still changes are required to work well with repeated case.

**Comment by t9md** [comment]
Finished for full-scroll(`c-f, b`) and  half-scroll(`c-u, d`)
Configuration option is provided independently.
Since as user, I want enable smooth for half, but don't want to enable for full scroll.

For `n` and `N`, I will decide after getting feedback for this scroll enhancement.

**Comment by t9md** [comment]
released as v0.60.0, give me feedback if you noticed something to improve.

**Comment by t9md** [comment]
Tried smooth-scroll for `ctrl-d` and `ctrl-u` for a couple of days, but I disabled to default.
For me it was not comfortable.

I have idea to improve UI effect to give context further, but I lack skill for CSS animation and not much motivated to learn it over other vmp stuff in my backlog.

How about @jordwalke  you tried?

**Comment by t9md** [comment]
Done for `ctrl-d` and `ctrl-u`.
I myself prefer non-smooth-default-scroll.

For `n`, `N`, open separate issue.

**Comment by jordwalke** [comment]
I like it - but I wish it didn't flash the line that it jumps to.

**Comment by t9md** [comment]
OK thanks for your feedback.

**Comment by t9md** [comment]
Removed flashing effect, will be included in next release.
