### ISSUE TITLE
Shift width not pulling from Atom general preferences

### ISSUE THREAD

**Issue by jeremyrambo** [t9md/atom-vim-mode-plus#436]
-  **vim-mode-plus Version** 0.60.0
-  **Atom Version:**
 - Atom    : 1.10.2
 - Electron: 0.37.8
 - Chrome  : 49.0.2623.75
 - Node    : 5.10.0

When I use the command `>>` to indent one or more lines of code, it seems to do only do a hard tab style of shift equal to 4 columns.  Is there a way to configure vim-mode-plus to either (a) use the already configured options in Atom or (b) execute a command like: `:set softtabstop=2 shiftwidth=2 expandtab`?

Thank you for building such an awesome plugin!

**Comment by t9md** [comment]
Vim-mode-plus already use Atom's configuration option, so your issue is not unexpectedbehavior.
I cannot check in my notebook for now but following is what i want you check and respond.

- sample text(before/after keystroke)
- keystroke
- make sure atom's native indent command works differently than vim-mode-plus if so that's bug of vim-mode-plus, if not it's atom's issue(may be defradation)

**Comment by jeremyrambo** [comment]
This ended up being an issue with babel-loader which overrides the tab size for .js and .jsx extensions.  Changed this in the configuration CSON file and I'm back up and running. 

Thanks for your quick response!
