### ISSUE TITLE
Support "g0", "g$" and "g^"

### ISSUE THREAD

**Issue by propet** [t9md/atom-vim-mode-plus#443]
Motions "g0", "g$" and "g^" in vim, go to first character, last character, and first not blank character of **display line** respectively. Currently, this same motions in vim-mode-plus go to first character, last character, and first not blank character of **real line** respectively.

It would be nice to have the vim behaviour in atom as well.

btw, great package! :+1: 

atom-version: 1.10.2
vim-mode-plus-version: 0.60.1

**Comment by zethodderskov** [comment]
I would love this as well. 

Luckily, I found [this post](https://github.com/t9md/atom-vim-mode-plus/issues/724) that explains how to go up/down one visual line in Atom. I'm writing it here, because it was by accident that I found the solution - and my countless Google-search attempts didn't index anything. 

But these functions would be nice as well.

**Comment by thouqht** [comment]
This would be very useful since I use atom mainly for prose where the lines are wrapped.

**Comment by t9md** [comment]
I'll work for this from now.
