### ISSUE TITLE
Input Source should be disabled in command mode

### ISSUE THREAD

**Issue by Atry** [t9md/atom-vim-mode-plus#446]
All commands are broken in command mode if an Input Source is activated.

atom-vim-mode-plus should disable Input Source in command mode.

![screen shot 2016-10-24 at 18 21 45](https://cloud.githubusercontent.com/assets/601530/19642239/ffaebde6-9a16-11e6-8897-19d168f25296.png)

The snapshot shows the broken commands when I press `l` repeatedly if an Input Method is activated. The commands should have moved right the cursor if this bug is fixed.

* Atom version: 1.10.2
* vim-mode-plus version: 0.61.0

**Comment by t9md** [comment]
Once I tried and partially success, but reverted because of more critical error(I can't remember what it was)
If you want to know detail, read following.

https://github.com/t9md/atom-vim-mode-plus/issues/148
atom/atom#1092


Btw vim-mode-plus currently not trying to fix this because I couldn't find good way(was tried and failed).

Also following blog is worth to read(I haven't tried by myself).
It's seems to explain the way to disable IME when escape insert-mode.
It's written in Japanese, but Karabiner's manual have english version so you can try by your self.

http://yamacent.hatenablog.com/entry/2015/04/22/235114

**Comment by Atry** [comment]
Thank you.

**Comment by heyeshuang** [comment]
Hello, 

I found a package named [atom-vim-mode-plus-auto-ime](https://atom.io/packages/vim-mode-plus-auto-ime), which could run a custom command when the mode changes. For all the three operating systems, there are commands to switch IMEs:

* macOS: [input-source-switcher](https://github.com/vovkasm/input-source-switcher)
* Linux: `fcitx-remote` for `fcitx`
* Windows: a [script](https://github.com/heyeshuang/ime_helper) which sends message to the window

Just wrote a [post](https://heyeshuang.github.io/blog/2017/09/05/atom-vim-mode-auto-switch-ime/) for this and hope it may help.

**Comment by t9md** [comment]
@heyeshuang I read and tried auto-ime pkg, thanks for sharing your knowledge, great article!
