### ISSUE TITLE
Can't see cursor in visual mode

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-vim-mode-plus#45]
(Sorry for filing many issues at the same time. I'm still very new to Atom and a friend recommended this plugin, please redirect me to the correct place if I'm filing the wrong stuff! Thanks)

Selection using `V` makes the cursor disappear:
![screenshot 2015-12-06 17 16 40](https://cloud.githubusercontent.com/assets/1909539/11615988/2da23152-9c3d-11e5-8a54-144d823b722f.png)
 which makes jumping around with selection beginning/ending with `o` much more difficult. I guess it's placed too far to the right?

**Comment by t9md** [comment]
In atom, when you select line(like `V` in vim-mode-plus), it put cursor on first column of **next** line.

e.g. select line 3(internally, row=2 since index start from 0)

It put cursor on point row=3, column=0.
If I make cursor visible, it definitely confuse user since cursor is shown at **next** line of selected line.
To solve this confusion, I have to build cursor management system specially for vim-mode-plus's linewise selection.

I don't have motivation to do that, its too much.
So, until Atom began to provide the way to solve this hurdle, I won't **FIX** this.

**Comment by t9md** [comment]
I came up wtih an idea.
Instead of showing cursor in visual-linewise mode, highlight head line of selection(not tail).
This allow user to easily understand which is head of selection when type `o`.

**Comment by t9md** [comment]
![](https://raw.githubusercontent.com/t9md/t9md/54870ed83d9256b50ba9812851a96c7c36180842/img/vim-mode-plus/show-cursor-in-visual-lineiwse.gif
)

Some progress, but need further bug scrubbing...

NOTE, in visual-linewise mode move left and right by `l`, `h` is not work unlike Vim.
It only indicate column which you will land when escaped to nomal-mode.

**Comment by chenglou** [comment]
Good stuff, thanks for the responsiveness =)

**Comment by t9md** [comment]
will be included in next release
