### ISSUE TITLE
`" a y` does not correctly save to 'a' register when used with input-taking-motion like 't'

### ISSUE THREAD

**Issue by plbowers** [t9md/atom-vim-mode-plus#520]
named buffer `a` contains "hello world"

TEXT:
This +is a line and a 3 followed by text

My cursor is at + and I want to yank the text from there to the 3 and put it in named buffer a:

`"ayt3`

Now I put the contents of named buffer `a` somewhere

`"ap`

I get "Hello World" instead of "is a line and a " - the yank did nothing

I should add that sometimes that same yank command does work, but most of the time it does not. I have not figured out reliably why it works sometimes and sometimes not.

**Comment by t9md** [comment]
What you are saying **buffer* is **register* in correct term.
This is  bug similar to #491, because of current `vimState.input` is inappropriately re-used, which I have to fix with high-priority.
This is dirty fix, will be available in next release(but release is available only in v1.13.0-beta or later).
If you are using stable v1.12, please wait to v1.13 become stable.
