### ISSUE TITLE
Keyboard centric notifications experience.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#526]
Have you thought of a way to improve Atom notifications through `vmp`? I'd love to see your approach to the problem. Atom's notifications are currently far too spammy and distracting, and *not at all* keyboard friendly. I wonder if `vpm` could one day have a lightweight alternative to the default notification renderers (I'm thinking something like [this](https://github.com/atom/notifications/issues/29) but done in `vmp` style (keyboard-centric, and unobtrusive).

**Comment by t9md** [comment]
Most notifications are dismissable by `core:cancel`.
But sometime `escape` is mapped to other command in different scopes.
So I use `ctrl-g` as alternate key for `core:cancel`.
`ctrl-g` is my custom from when I was emacs's user.

So by setting `ctrl-g` to different scopes.
I can always invoke cancel by `ctrl-g` including dismiss noisy notification via keybord.

```coffeescript
'atom-workspace:not([mini])':
  'ctrl-g': 'core:cancel'
'.select-list':
  'ctrl-g': 'core:cancel'
'atom-text-editor.vim-mode-plus.insert-mode.autocomplete-active':
  'ctrl-g': 'autocomplete-plus:cancel'
'atom-text-editor.vim-mode-plus-search':
  'ctrl-g': 'vim-mode-plus:search-cancel'
```

Btw, what I can imagine from you suggestion to make it keyboard friendly.
Just dismiss-notifcation-on `rest-normal-mode` command which is mapped to `escape`.
Currently `hlsearch`, `persistent-selection`, `preset-occurrence-marker` can be cleared thorguh this command, so `clearNotificationOnResetNomalMode` config option can be easy.
But I basically don't want to touch outer-vmp-world since it's gateway-to-road-to-disastrous-mess.

**Comment by jordwalke** [comment]
Yeah, I understand. One detail: I'm not sure I would want to clear notifications whenever I reset normal mode. If I am in in insert mode, with search results highlighted, and with a notification open. I would want to have the following happen:

- First escape causes enter normal mode.
- Second escape will clear search highlight.
- Third escape closes notifications.

Even then, I'm still not happy with the experience that I just proposed. I see problems with it.
I'm realizing that I wouldn't care so much about being able to dismiss them via keyboard if there was a better user experience for notifications to begin with - one that was keyboard driven, and didn't flash annoying banners on top of my code/tabs. I think fixing notifications from the ground up is the real solution - not introducing complexity in `vmp` to work around the poor user experience of notifications.

I with someone would apply @t9md's approach to optimized, keyboard driven workflows, for the notification experience 😄

**Comment by t9md** [comment]
Nothing to do at vmp side for now. So close with not-resolved labeled.
