### ISSUE TITLE
Question: vim-commentary bindings?

### ISSUE THREAD

**Issue by nwaywood** [t9md/atom-vim-mode-plus#547]
I am trying to emulate the [vim-commentary](https://github.com/tpope/vim-commentary) bindings (e.g. `gc` operator and `gcc` to comment a line). I have managed to get `gc` to work since its the same operator as the built-in `g/` operator:

```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
    'g c': 'vim-mode-plus:toggle-line-comments'
```

but I'm not how to get `gcc` to work. Essentially I want to bind `gcc` to `g/al` but obviously the following doesn't work:

```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
    'g c c': 'g / a l'
```

Is this possible?

And thanks for the amazing plugin btw!

**Comment by t9md** [comment]
#### Way-1: easiest. use native `editor:toggle-line-comments`

```coffeescript
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'g c': 'vim-mode-plus:toggle-line-comments'
  'g c c': 'editor:toggle-line-comments'
```

#### Way-2: map `c` to  `toggle-line-comments` in `operator-pending-mode`

When same operator is executed twice like `d d`, `g U g U`, `y y`,
It works on linewise, so the benefit of this is it can take count N.

```coffeescript
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'g c': 'vim-mode-plus:toggle-line-comments'

'atom-text-editor.vim-mode-plus.operator-pending-mode':
  'c': 'vim-mode-plus:toggle-line-comments'
```

#### Way-3: map `c` to  `toggle-line-comments` in `operator-pending-mode.toggle-line-comments-pending`

This is similar to Way-2 but using more granular keymap scope.
This is better since you can map `c` on `operator-pending-mode` to other command.
Only when `toggle-line-comments` is waiting for target, your `c` is mapped to `toggle-line-comments`.

```coffeescript
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'g c': 'vim-mode-plus:toggle-line-comments'

'atom-text-editor.vim-mode-plus.operator-pending-mode.toggle-line-comments-pending':
  'c': 'vim-mode-plus:toggle-line-comments'
```

**Comment by nwaywood** [comment]
Thankyou I got it working using way-3. I understand how this plugin works a little better now too. When I have some free time I might look into adding some other operators that I miss from vim with that `operator-pending-mode` selector
