### ISSUE TITLE
Replacing (r hotkey) doesn't work properly with russian keyboard layout

### ISSUE THREAD

**Issue by ousennin** [t9md/atom-vim-mode-plus#643]
# Check list

- Atom version info(`atom --version`) - 1.12.7
- vim-mode-plus version - 0.66.1
- Restarting Atom itself solve your problem? - No, restarting doesn't help

The problem is following: when I'm trying to use replacing (r) with russian keyboard layout on, the replacing mode turns on, but input is in english (I can't type russian letters using replacing). It should be russian instead.

**Comment by t9md** [comment]
I know **why** this not work.
And want to fix, but currently this is limitation by vmp's design rather than bug.

I know how to fix this, and I believe this was **WORK** in older version of vmp.
So If you try githubs' [vim-mode](https://github.com/atom/vim-mode), it should work.

Why vmp not support this is, currently vmp read user-input via key [keymap](https://github.com/t9md/atom-vim-mode-plus/blob/master/keymaps/vim-mode-plus.cson#L268-L366).
I think this seems wired/strange, but have some background.

- For performance reason.
- So that user can override `m X` without breaking `m` command itself.

https://github.com/t9md/atom-vim-mode-plus/pull/448

I **want** solve your issue, but priority is not high unless we can do it without sacrificing above benefits.
