### ISSUE TITLE
unexpected caret motion after selecting Line w/mouse while in visual mode (triple click)

### ISSUE THREAD

**Issue by jonboiser** [t9md/atom-vim-mode-plus#654]
I've added a GIF to illustrate this. This behavior doesn't happen when I'm in insert mode. It also doesn't seem to happen for lines at the end of a file.

![triple click](https://cloud.githubusercontent.com/assets/10248067/21896068/0502430a-d8b3-11e6-98b6-5d9a8d350e85.gif)

The recorder doesn't visualize this well, but I'm clicking the line quickly multiple times. The normal behavior is:
Single click: caret on column
Double click: select whole word
Triple click: select whole line -> caret gets moved to the beginning of the line in visual mode

You'll also see that the caret sometimes move up one line when I click again to unselect the line.

If this is intentional behavior, is there a way to disable it?

# Check list

- Atom version info(`atom --version` 1.13.0
- vim-mode-plus version 0.79.0
- You disabled vim-mode? yes
- Tried to latest stable atom version with latest vim-mode-plus. yes
- Restarting Atom itself solve your problem? no
- Keybinding issue? don't know

**Comment by t9md** [comment]
> The recorder doesn't visualize this well, but I'm clicking the line quickly multiple times. The normal behavior is:
> Single click: caret on column
> Double click: select whole word
> Triple click: select whole line -> caret gets moved to the beginning of the line in visual mode

So what you want is DONT move first column on triple click right?

This is same issue when you do `cmd-l`(`editor:select-line`), column is set to start of that line.
Cursor placement for outer-vim-mode-plus command(none `vim-mode-plus:` prefixed command) have some limitation.
If you do `V` instead of `cmd-l`, you see, colmun is kept to original column.

> You'll also see that the caret sometimes move up one line when I click again to unselect the line.
>

OK, I could reproduce, but priority is VERY low.
Why?
 - vim-mode-plus is already doing very aggressive work to show cursor on visual-mode.
 - Mouse based operation is always low priority unless fixing it is very easy.

Native Atom don't show cursor if selection was not empty, and cursor position is **actually** always column 0 in visual-linewise mode.
vim-mode-plus' dynamically tweaking cursor offset to show cursor on desired column.
So unless I can find better solution to this cursor styling in visual-mode, I don't want to go further(keep away from doing more special-work)

> If this is intentional behavior, is there a way to disable

No

**Comment by t9md** [comment]
> You'll also see that the caret sometimes move up one line when I click again to unselect the line.

I think this part is now fixed.

And I'm not clear for original issue.
What was that?
Latest vmp respect original selection's cursor position on mouse click, that means, vmp's cusor position when starting visual-mode from mouse click is sync with Atom's native behavior.
I cannot enhance this part any more.
