### ISSUE TITLE
In visual block mode selection is shifted to the right on lines with tabbed indent.

### ISSUE THREAD

**Issue by esoniq** [t9md/atom-vim-mode-plus#662]
# Check list

```
atom --version
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
**vim-mode-plus version:** 0.80.0
**vim-mode:** disabled
**restarting:** does not help

Occurs when going up or down in Visual Block mode through a file with TAB indent. Rectangular selection is expected, but each additional level of tabbed indent makes selection shift to the right by one character. Please, see the screenshot bellow, I've enabled invisible characters specially to demonstrate this case (lines 3, 4 and 5 have TABs in the beginning).

![2017-01-25_14-42-33](https://cloud.githubusercontent.com/assets/3876236/22291187/a656a1ec-e30d-11e6-83b5-8f87b476efb8.png)

**Comment by stevengubler** [comment]
Me too. However, I've noticed this problem everywhere, not just in visual block mode. (though it is definitely most noticeable there)

I believe that this is happening because when you ask the cursor to go down a line, for example, the cursor increments it's line _but doesn't recalculate what it's offset into the line should be._ If every character were the same width, then this wouldn't be needed, but tabs are a weird character because their offset is (generally) more than 1.

To move up and down lines properly, the cursor should calculate some sort of **true index** offset which would be the normal offset  increased by some amount for every tab before the cursor on a line. (e.g. 3, if tab spacing is 4)

**Comment by t9md** [comment]
I'm now overhauling this part.
After finished, I'll check above comment and fix if still have problem after overhauling.
Thanks for reporting.

**Comment by t9md** [comment]
I know there is bug in visual blockwise mode.
But I don't see the issue you reported  if I disabled **Atomic Soft Tabs**.
Atomic Soft Tabs is enabled by default, I use this disabled from this become configurable for a long time ago.

So I tend to overlook bugs in AtomicSoftTabs enabled situation.

<img width="1072" alt="settings_ ___github_atom-vim-mode-plus_atom-vim-mode-plus-copy" src="https://cloud.githubusercontent.com/assets/155205/24213114/bd05c5e2-0f74-11e7-8a85-3f4bbf6a3cc7.png">

**Comment by esoniq** [comment]
You are probably using soft tabs. I use hard tabs and I have an issue regardless of Atomic Soft Tabs option.

**Comment by t9md** [comment]
Oh, you are correct. agree.

**Comment by t9md** [comment]
Your original reported issue is still exists even after I overhauled blockwise-selection.
And I know how to fix, but I need more basic broken part fixed before supporting hard-tab.
I understand hard-tab text support in blockwise-mode is also basic part of Vim, but it need time to fix.

Will keep open until fixed.

**Comment by stevengubler** [comment]
Any updates on this issue? It's been a while...

**Comment by t9md** [comment]
Finally I decided to fix this.
Sorry for you to wait LOOONG TIME.

**Comment by t9md** [comment]
- PR #1052 is to fix inaccuracy of Blockwise selection(`visual-blockwise-mode`).
- `j`, `k` inaccuracy in hardTabbed editor was fixed in https://github.com/t9md/atom-vim-mode-plus/commit/3b8193c06f009a01addf3b3df16f0c5721d3073f
