### ISSUE TITLE
Cursor positioned after selection in visual selection modes

### ISSUE THREAD

**Issue by axelson** [t9md/atom-vim-mode-plus#718]
# Check list

- Atom version info(`atom --version`)
    - 1.15.0
- vim-mode-plus version.
    - 0.85.1
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
    - yes
- Tried to latest stable atom version with latest vim-mode-plus.
    - yes
- Restarting Atom itself solve your problem?
    - no
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
    - no
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

I'm not sure exactly when this started happening but a couple of weeks ago the cursor started to be positioned after the current selection. This is most noticeable on visual line mode. So starting with the text:

```
Simple text file
Two lines
```

And the cursor on the first line and pressing `V` I would expect the first line to be selected and the cursor to be at the end of the first line. Instead while the first line is selected, the cursor is at the beginning of the second line. This also affects normal and block visual selection modes.

Here is a screenshot after pressing `V`
![screenshot 2017-03-27 14 52 53](https://cloud.githubusercontent.com/assets/9973/24384189/ba4bfaf6-12fd-11e7-9541-04da116cdbde.png)

**Comment by t9md** [comment]
![v0 85 1-v](https://cloud.githubusercontent.com/assets/155205/24406191/95ee9956-1402-11e7-8b83-f718dd2fb8b5.gif)

Can't reproduce, How can I reproduce, my env is here.

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.3
BuildVersion:   16D32
$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by t9md** [comment]
Btw, you enabled this vmp setting?

<img width="390" alt="settings_coffee_ ___github_atom-vim-mode-plus" src="https://cloud.githubusercontent.com/assets/155205/24406483/57836d4e-1403-11e7-8547-d9a0b9caebf1.png">

If not enabled, the issue you began to see is because of Atom's default behavior change,

- Before Atom v1.15.0, atom hide cursor when selection is not empty.
- From Atom v1.15.0, atom shows cursor even when selection is not empty.

This behavior is configurable in setting-view's Editor section.

<img width="330" alt="settings_ ___github_atom-vim-mode-plus" src="https://cloud.githubusercontent.com/assets/155205/24406650/90fafede-1403-11e7-83a9-668c71bb13c1.png">

**Comment by axelson** [comment]
@t9md ah, "Show Cursor in Visual Mode" in vmp settings fixed it! I don't remember toggling that off so I'm not sure how it became disabled. Thanks for the help and the excellent plugin!
