### ISSUE TITLE
Consistent surround behavior with vim-surround

### ISSUE THREAD

**Issue by ethanluoyc** [t9md/atom-vim-mode-plus#75]
I find that the surround commands of the `vim-mode-plus` different from that of `atom-vim-surround` or the original `vim-surround`

For example, 
the `vim-mode-plus:surround` does not follow that of `vim-surround`

Say I bind this function to to `y s` in normal mode, in `vim-surround` you will then specify the text object before specifying the character you want to surround. However, `vim-mode-plus:surround` precedes the typing of the surrounding character before the text object. Therefore, to surround a word say `hello` to become `'hello'`, I would press `ys'iw` in  `vim-mode-plus` but `ysiw'` in `atom-vim-surround`. Is this an expected parity?

**Comment by bronson** [comment]
There's some discussion about surround here: https://github.com/t9md/atom-vim-mode-plus/issues/54#issuecomment-163736562

I agree.  :)

**Comment by t9md** [comment]
Oh, I didn't realized this inconsistency.
Since I haven't check tpope's surround and atom-vim-surround behavior, I just implemented how I think it should be.

Aside from muscle memory, I like current vim-mode-plus's implementation since it follows `operation complete at the timing you provided final target(text-object/motion)`.
But vim-surround, atom-vim-surround require extra input after target(text-object/motion) specified.

How do you guys think?
I also trying to find solution like providing config option switch( but I wan to avoid adding many switch ...)

**Comment by t9md** [comment]
I experimentally implemented new config option `readTargetFirstOnSurround`.
By enabling this potion, surround behave like vim-surround.
But I'm not still sure how much this feature is important, at least I don't need and I want to avoid unessential feature/config scattered on code decrease maintainability..

**Comment by t9md** [comment]
I'm getting feel vim-surround compatible behavior more make sense.
Since keystroke `iw`, `ip`, `il`(inside-line) comes just after operator like `v`(this is implicit operator), `d`, `ys`(when you map ys to `vim-mode-plus:surround`).
But I don't want two scenario in this behavior, I'm in mood to make new vim-surround compatible behavior as default behavior and remove old behavior.

Anyway I decided to merge this branch first.

**Comment by t9md** [comment]
I picked original suggestion of this issue.
Chose compatible behavior.
Thanks for catching this, when @bronson spot this issue, I thought you are saying about internal implementation, so I didn't get your point. :cry:

**Comment by bronson** [comment]
Oh, that helps me understand your reply.  :)  Glad to hear it!

**Comment by geksilla** [comment]
Hi @t9md I'm using version 0.10.2 and surround keymaps like `y s i w (` and `d s (` don't work for me until I uncomment [ys](https://github.com/t9md/atom-vim-mode-plus/blob/master/keymaps/vim-mode-plus.cson#L216), [ds](https://github.com/t9md/atom-vim-mode-plus/blob/master/keymaps/vim-mode-plus.cson#L218), [cs](https://github.com/t9md/atom-vim-mode-plus/blob/master/keymaps/vim-mode-plus.cson#L219) keymaps.

**Comment by t9md** [comment]
Yes I intentionally disabled by default. Since its not native Vim feature.

**Comment by geksilla** [comment]
Got it. And how to perform surround actions now?

**Comment by fabiomcosta** [comment]
I'm with the same issue, sorry to ask for this, but can you document what are the alternatives to have `surround` working again?

**Comment by fabiomcosta** [comment]
OK I got it working.
Go to Settings -> `your keymap file`
Make it look like this: https://gist.github.com/fabiomcosta/90a80134e85282b38853

**Comment by kingluddite** [comment]
@fabiomcosta Worked like a charm but fyi - you have duplicate keys in your [gist](https://gist.github.com/fabiomcosta/90a80134e85282b38853)

```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'y s': 'vim-mode-plus:surround'
  'y s w': 'vim-mode-plus:surround-word'
  'd s': 'vim-mode-plus:delete-surround'
  'c s': 'vim-mode-plus:change-surround'
  'd s': 'vim-mode-plus:delete-surround-any-pair' # here
  'c s': 'vim-mode-plus:change-surround-any-pair' # here
```

**Comment by t9md** [comment]
We also have this.

https://atom.io/packages/vim-mode-plus-keymaps-for-surround
