### ISSUE TITLE
After key 's' in visual mode, selection block not canceled

### ISSUE THREAD

**Issue by MewX** [t9md/atom-vim-mode-plus#787]
# Check list

- Atom version: 1.17.0 x64
- vim-mode-plus version: 0.92.1
- Your OS: Win10 15063
- You disabled vim-mode? Disabled
- Tried to latest stable atom version with latest vim-mode-plus: Yes
- Keybinding issue? No, it's logical issue

----

To reproduce the issue, I'll use `[]` to present cursor in normal mode, and `|` in insert mode.

Originally:
```
some text;
[d]ist = a;
pastNodes = b;
```

Then press `c-v`, select:

```
some text;
[dist] = a;
[past]Nodes = b;
```

Then press `s`:
```
 some text;
| = a;
 Nodes = b;
```

Then press `esc`:
```
[s]ome text;
[ ]= a;
Nodes = b;
```

See, **the selection block are not canceled**, if I press `esc` again, it becomes normal:
```
some text;
[ ]= a;
Nodes = b;
```

**Comment by t9md** [comment]
![issue-vb](https://cloud.githubusercontent.com/assets/155205/26443160/42ad1d06-4172-11e7-9609-aa6201c3e4a7.gif)


I can't understand what your issue is.

Which is your issue?
A. After `escape` on visulal-block mode, vmp still remain in visual-mode.
B. After `escape`, multiple cursor created during visual-block-mode remain uncleared.

If B, you can change it via `clearMultipleCursorsOnEscapeInsertMode` vmp config.

NOTE: This feature have issue for the correct cursor placement after escape, it's already another issue.

**Comment by MewX** [comment]
Thanks, I meant B, but I think this feature should be turned on by default as it acts different from native vim.

**Comment by t9md** [comment]
> Thanks, I meant B, but I think this feature should be turned on by default as it acts different from native vim.

I have different opinion for this feature.
I understand the background of you.
But keeping cursor after visual-block-mode have some goodness, I'll keep this default until I finished #608.
