### ISSUE TITLE
how i use paste in the Search line?

### ISSUE THREAD

**Issue by TimLeaf** [t9md/atom-vim-mode-plus#791]
I'm sorry for this question.
I want to use Paste(ctrl-v) in the Search line("/" key).
But it doesn't works. Help me.
Thanks.

**Comment by t9md** [comment]
Sorry, this is because I override `ctrl-v` at search input.
Will fix in next release.
Until then, you can set following keymap in your `keymap.cson` to workaround this bug.

```
'atom-text-editor.vim-mode-plus-search':
  'ctrl-v': 'core:paste'
```

**Comment by TimLeaf** [comment]
Thank you very much!

**Comment by dylnmc** [comment]
note: I don't suppose it would work all the time, but there is a register that stores the last selection. This works within atom and in linux (if enabled -- which it is by default in a modern x session, or it should be). I'm not sure about OSx. You cab "paste" the contents in atom or linux by pressing <kbd>shift</kbd>+<kbd>insert</kbd>.

Also, when you do `yiw` (e.g.) and use the "yank register" in *vim-mode-plus* it yanks to the system clipboard (`+` register -- accessed with <kbd>ctrl</kbd>+<kbd>v</kbd>) and to the selection clipboard (`*` register -- accessed with <kbd>shift</kbd>+<kbd>insert</kbd>).

<kbd>shift</kbd>+<kbd>insert</kbd> works in search (`/`) mode.

Therefore, you could probably use <kbd>shift</kbd>+<kbd>insert</kbd> in search mode most times. because if you have copied something, and you used a mouse to do so, you almost certainly selected it, and it was, therefore, stored into the selection register.

p.s. sorry if I misuse the name "selection register." I'm not quite sure what it's called, but hopefully, point taken.

cheers,
dylnmc

**Comment by t9md** [comment]
@dylnmc Thanks, for helping as always!
I didn't know that usage of register! learned from you.
