### ISSUE TITLE
Visual Mode Breaks Sometimes on Soft Wrap

### ISSUE THREAD

**Issue by chibicode** [t9md/atom-vim-mode-plus#81]
atom-vim-mode-plusの開発、お疲れさまです。いつも愛用しています。

こちらのFira Codeを利用しているのですが、
https://github.com/tonsky/FiraCode

Fira Codeにした途端、Visual Modeの挙動が少しおかしくなるみたいです (v0.10.1)。

たとえばFira Codeを利用している状態で以下のMarkdownファイルを開き、

```md
# react-simple-format

The port of Rails's [simple_format](http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format) to React.

## Usage

Turns double newlines into different paragraphs. See [examples](examples) for live examples.
```

`Usage`の右端にNormalモードでカーソルを合わせ、`v`でvisual modeに入ると、`h`で左に行こうとすると左全てを選択してしまい、また一旦`h`を押すと、`l`で右に戻れません。コマンドはちゃんと認識されているみたいなのですが。

![](http://cl.ly/1g1c2j3L1f1g/Screen%20Recording%202015-12-22%20at%2011.35%20PM.gif)

**Comment by t9md** [comment]
うーむ、、なぜでしょうかね。
私も FiraCode いれて試してみました。`fontFamily: "Fira Code"`
画面の通り問題の事象を起こせません。

![firacode](https://cloud.githubusercontent.com/assets/155205/11959214/814534a6-a90f-11e5-8572-b7000e1f3809.gif)

vim-mode だと同じ事象起きますか？vim-mode-plus 固有なら vim-mode からのデグレなので調査はしやすいです。あと、他のパッケージを疑って削ってみて事象が解消するかどうか。

**Comment by chibicode** [comment]
早速のご返事ありがとうございます。vim-modeだと起こらないようです。下の通りKeybindingを全部消しましたがあまり関係ないですね・・・

![](http://cl.ly/1z0T043Y1P2i/Screen%20Recording%202015-12-23%20at%2011.50%20AM.gif)

他のpackageに原因がないか調べてみます。

**Comment by chibicode** [comment]
Package全部無効化しましたがこの現象がおきますね・・・ちなみにAtomのバージョンは1.3.2、vim-mode-plusは0.10.1です。

![](http://cl.ly/2w273c450T2I/Screen%20Recording%202015-12-23%20at%2012.54%20PM.gif)

**Comment by chibicode** [comment]
Soft Wrapが原因だということがわかりました。下のコードだと、3行目が1行分Wrapしてるときに問題が起きていて、Wrapがないときは大丈夫です。

![](http://cl.ly/0q1C3t221t1n/Screen%20Recording%202015-12-23%20at%2012.59%20PM.gif)

ただ、複数行Wrapしていると逆に大丈夫です。

![](http://cl.ly/0a2B1G3H1x00/Screen%20Recording%202015-12-23%20at%2012.59%20PM.gif)

**Comment by t9md** [comment]
原因調査、ありがとうございます。v0.9.1 では発生しないので、デグレですね。
すみません。再現出来たので、直します。

**Comment by chibicode** [comment]
@t9md ありがとうございます！感謝です。

**Comment by gnl** [comment]
I just wanted to report the same issue (I think it's the same - can't really follow the conversation so far) - visual mode seems to be breaking for me as well on soft-wrapped lines, for example I'll do a 'vw' and it'll select back to the beginning of the line. Not always though, sometimes it'll jump to a random point in the middle of the line, haven't been able to figure out why it does one thing or the other.

I'm using Fira Mono as a font with enabled ligatures - if that matters, I can test with other fonts as well.

**Comment by t9md** [comment]
@gnl The cause is the bug I introduced in v0.10.0. And also I noticed some minor bug introduced in v0.9.0 for softwrap cant wrap next line when move right at eol when use enabled wrapLeftRightMotion config.
Both are based on some bad handling about screenPosition and bufferPosition translation.
Font setting is irerelevant.
Sorry for this inconvenience.
I think I can release fix in tomorrow.

**Comment by t9md** [comment]
Here is fix NOTE(for the purpose of I can refer later)

This is the bug introduced in #79 which introduce screenPoint clipping ability to find valid cursor position when point is between indentation white-space, but in this clipping procedure, I simply passed bufferPosition but I should use screenPosition, screenRange since this feature is only provided via `displayBuffer::clipScreenColumn`.

This bad position translation cause issue cursor seem go semi-random position when moving cursor left/right in visual-mode and on soft-wrapped buffer.

**Comment by chibicode** [comment]
@t9md thank you!

**Comment by t9md** [comment]
Released as v0.10.2.
