### ISSUE TITLE
Unable to use dt$ or ct$ in tex file 

### ISSUE THREAD

**Issue by dionyziz** [t9md/atom-vim-mode-plus#816]
Steps to reproduce:

1. Create a new TeX file and save it as `test.tex`
2. Type the following single line in it:
```
a $test$
```
3. Move the cursor to the beginning of the line
4. Type dt$

Expected behavior: The part "a " is deleted.
Actual behavior: A "$" is inserted.

A similar error exists for ct$

I am using atom-latex.

# Check list

- Atom version info(`atom --version`)
```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
- vim-mode-plus version: `0.95.0`
- Your OS(e.g. macOS Sierra 10.12.3): `macOS Sierra 10.12.5`
- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously: Yes.
- Tried to latest stable atom version with latest vim-mode-plus: Yes.
- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

**Comment by t9md** [comment]
Tried to reproduce, but I coldn't.
I can used `d t $`, `c t $` as expected.

Below is kesytroke and mapped command when I did `d t $`.

<img width="666" alt="tryit_hoge_tex_ _tryit_ ___tryit" src="https://user-images.githubusercontent.com/155205/28655049-e58d3578-72d3-11e7-91f8-d1e2723b4990.png">

How do you type `$` character in your keyboard?

Manually invoking command work?

1. `d`
2. `t`
3. `shift-cmd-p` to start command-pallate then execute `Vim Mode Plus: Set Input Char $`.

Because of some history, vmp read `$` char in peculiar way(not just `$`, all char for `f` and `t` motion).
It' actually done through keymaping like bellow.

```coffeescript
'atom-text-editor.vim-mode-plus-input-char-waiting':
  '$': 'vim-mode-plus:set-input-char-$'
```

So when you type `$` in your keyboad, that keystroke must fire above keybinding.
Observe keybinding-resolver(start it `cmd-.` if you are macOS), then find how Atom recognizing your `$` keystroke, then remap it in your `keymap.cson`(replace above keymap's `$` part to the char you found it from keybinding-resolver).

**Comment by dionyziz** [comment]
Manually invoking the command using `d`, `t`, then `shift-cmd-p` and `Vim Mode Plus: Set Input Char $` does the correct job.

I am typing `$` by holding down Right Shift and then pressing the `4` button above the main row. The same problem exists if I use Left Shift.

Do you have atom-latex installed? Perhaps it's related to it. If I don't save the file as a .tex file, the problem does not occur.

**Comment by t9md** [comment]
I don't think atom-latex is related.
Have you checked keybinding resolver?

Your issue is "when you type `$` it's not recognized `$` by atom's keymaps system".

So solution is as I wrote, 1. observe result of keybinding-resolver, 2. then set your `keymap.cson`.

What OS are you using? What type of keyboard layout are you using?

**Comment by t9md** [comment]
OK I could reproduce it, `atom-latex` is overriding `$`, that's issue.

**Comment by t9md** [comment]
Currently, atom-latext is overwriting following **non-modifier-combined** keymap.

```cofeescript
"atom-text-editor[data-grammar~='latex']":
  '$' : 'atom-latex:tools-dollarsign'
  '`' : 'atom-latex:tools-backquote'
  '"' : 'atom-latex:tools-doublequote'
```

You have some option A or B or C to fix it.

- A: disable keymap from `atom-latext`'s setting-view, let checkbox off for `Keybindings` section, then define necessary keymap by your self.
- B: Re-overwrite keymap in your `keymap.cson`, this file is always prioritized over keymap defined by package.
- C: report atom-latex to not override normal key by default


TO do B. here is keymap you have to paset your `keymap.cson`
```cofeescript
"atom-text-editor.vim-mode-plus-input-char-waiting":
  '$' : 'vim-mode-plus:set-input-char-$'
  '`' : 'vim-mode-plus:set-input-char-`'
  '"' : 'vim-mode-plus:set-input-char-"'
```
