### ISSUE TITLE
Make cursor movable in visual-linewise mode

### ISSUE THREAD

**Issue by t9md** [t9md/atom-vim-mode-plus#83]
I came up with idea, so try.
This is same topic reported in #74 .

**Comment by t9md** [comment]
![charwise-move-in-linewise](https://cloud.githubusercontent.com/assets/155205/11981171/92236bec-a9e3-11e5-9a03-1118eff11f04.gif)

Surprisingly enough, I could achieve characterwise-movement in visual-linewise without big mess.
Using characterwise move as base mode while modifying selection then restore linewise range when selection modification finished.
Base mechanism for this is already implemented to achieve submode shift.
So what I did here is just leverage this charwise preserve/restore mechanism in visual-linewise.

@bronson
Could you check behavior from master repository before publishing?
Since this is big change, I want to double checked.

**Comment by bronson** [comment]
Oops, I accidentally left my comment in #74.

Very nice, looks great.  "big" change?  :)

**Comment by bronson** [comment]
One *super minor* difference from Vim: when hitting `/` to extend a linewise selection to a match, it selects the correct line but it doesn't move the cursor to the correct column (the start of the match).  Vim does.  Doing this with characterwise select works correctly.

To reproduce: in your gif above, start at the end of line 107, hit `V`, and then hit `/move`.  Your selection correctly extends to line 110, but the cursor remains on column 20 instead of jumping to the `m` in `move`.

But this is still super shippable without this fix.

**Comment by t9md** [comment]
I couldn't reproduce issue you reported.
But I noticed, several case I need to improve, but I want to treat it as distinct topic one-by-one.
So close this case.

**Comment by t9md** [comment]
> Very nice, looks great. "big" change? :)

Not about amount of code, but affect broad range of operation, since until this enhancement `w`, `W`, `e`, `E`, `l`, `h` is actually ignored in visual-linewise mode.
So I'm afraid I'm missing unnoticed caveat. 
But I'm OK now, I released, and I can pick and fix one by one.(I noticed some issue in soft wrapped line.)

**Comment by bronson** [comment]
I can't reproduce the issue with 0.11.  Yay!  Not sure if it was fixed or there was something weird on my machine.

I'd written a unit test for it that still fails though, probably something with the unit test: #90
