### ISSUE TITLE
Multi Language problem

### ISSUE THREAD

**Issue by Malatest** [t9md/atom-vim-mode-plus#833]
#### Hey Thanks for working on such a great addon for Atom.
---
I have an issue with this package when I press **r** it changes current character only to latin symbol even though my keyboard layout is set to Russian. As a Developer from Russia it cripples me a lot. Hope you can fix it. Thanks in advance.

**Comment by t9md** [comment]
This is limitation, see comment in exact same issue.

https://github.com/t9md/atom-vim-mode-plus/issues/643#issuecomment-270576056

- Leaving this limitation unfixed is mainly because of performance.
- And my main interest for vmp is "as-code-editor" which is written in only ascii character(I understand it's not always the case though).

**Comment by t9md** [comment]
I **decided** to fix this!
Now working on...
